import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wiki: [
    'wiki',
    {
      type: 'autogenerated',
      dirName: 'plugin',
    },
  ],
  api:[
    'api',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ]
};

export default sidebars;
